// <auto-generated />
using System;
using BloodBankManagementSystem.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BloodBankManagementSystem.Migrations
{
    [DbContext(typeof(BloodBankContext))]
    partial class BloodBankContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BloodBankManagementSystem.Models.Billing", b =>
                {
                    b.Property<int>("BillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BillId"));

                    b.Property<DateTime>("BillDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BloodGroup")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HospitalName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentMode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("RatePerMl")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("RequestId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TransactionNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BillId");

                    b.HasIndex("RequestId");

                    b.ToTable("Billings");
                });

            modelBuilder.Entity("BloodBankManagementSystem.Models.BloodInventory", b =>
                {
                    b.Property<int>("InventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InventoryId"));

                    b.Property<string>("BloodGroup")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CollectionDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DonorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InventoryId");

                    b.HasIndex("DonorId");

                    b.ToTable("BloodInventories");
                });

            modelBuilder.Entity("BloodBankManagementSystem.Models.BloodRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<string>("BloodGroup")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HospitalName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InventoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RequestId");

                    b.HasIndex("InventoryId");

                    b.HasIndex("PatientId");

                    b.ToTable("BloodRequests");
                });

            modelBuilder.Entity("BloodBankManagementSystem.Models.Consent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConsentGiven")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DonorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("SignatureHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SignedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DonorId")
                        .IsUnique();

                    b.ToTable("Consents");
                });

            modelBuilder.Entity("BloodBankManagementSystem.Models.DoctorInformation", b =>
                {
                    b.Property<int>("DoctorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DoctorId"));

                    b.Property<string>("DoctorAddress")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("DoctorName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("EmailId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Qualification")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("DoctorId");

                    b.ToTable("DoctorInformations");
                });

            modelBuilder.Entity("BloodBankManagementSystem.Models.DonorRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Alcohol24Hours")
                        .HasColumnType("bit");

                    b.Property<bool>("AteRecently")
                        .HasColumnType("bit");

                    b.Property<string>("BloodGroup")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("BloodPressure")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("BloodTransfusion")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DoctorId")
                        .HasColumnType("int");

                    b.Property<string>("DoctorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DonationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DonationType")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<bool>("FillingWell")
                        .HasColumnType("bit");

                    b.Property<bool>("FitToDonate")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<bool>("HadFever")
                        .HasColumnType("bit");

                    b.Property<bool>("HasTattoOrPiercing")
                        .HasColumnType("bit");

                    b.Property<float>("Hemoglobin")
                        .HasColumnType("real");

                    b.Property<bool>("HistoryOfJaundice")
                        .HasColumnType("bit");

                    b.Property<string>("HospitalName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsBreastFeeding")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsMenustruating")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsPregnant")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastDonationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Occupation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PatientId")
                        .HasColumnType("int");

                    b.Property<bool>("PrevRejectedForDonation")
                        .HasColumnType("bit");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<bool?>("RecentDeliveryOrAbortion")
                        .HasColumnType("bit");

                    b.Property<bool>("RecentSurgery")
                        .HasColumnType("bit");

                    b.Property<string>("RelativeName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("RiskeyBehavior")
                        .HasColumnType("bit");

                    b.Property<float>("Temperature")
                        .HasColumnType("real");

                    b.Property<bool>("TestedHIVPositive")
                        .HasColumnType("bit");

                    b.Property<bool>("UnderTreatment")
                        .HasColumnType("bit");

                    b.Property<bool>("UsedAntibiotics")
                        .HasColumnType("bit");

                    b.Property<string>("WardNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("DonorRecords");
                });

            modelBuilder.Entity("BloodBankManagementSystem.Models.EmployeeInformation", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("EmailId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeAddress")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MobileNo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Qualification")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("EmployeeId");

                    b.ToTable("EmployeeInformations");
                });

            modelBuilder.Entity("BloodBankManagementSystem.Models.HospitalInformation", b =>
                {
                    b.Property<int>("HospitalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HospitalId"));

                    b.Property<string>("DoctorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HospitalAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HospitalContact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HospitalName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonContact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HospitalId");

                    b.ToTable("HospitalInformations");
                });

            modelBuilder.Entity("BloodBankManagementSystem.Models.PatientRecord", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientId"));

                    b.Property<int?>("BillId")
                        .HasColumnType("int");

                    b.Property<string>("BloodGroup")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("DiseaseName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("HospitalId")
                        .HasColumnType("int");

                    b.Property<string>("HospitalName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MobileNo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PatientAddress")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("PatientId");

                    b.HasIndex("BillId");

                    b.HasIndex("HospitalId");

                    b.ToTable("PatientRecords");
                });

            modelBuilder.Entity("BloodBankManagementSystem.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BloodBankManagementSystem.Models.Billing", b =>
                {
                    b.HasOne("BloodBankManagementSystem.Models.BloodRequest", "BloodRequest")
                        .WithMany()
                        .HasForeignKey("RequestId");

                    b.Navigation("BloodRequest");
                });

            modelBuilder.Entity("BloodBankManagementSystem.Models.BloodInventory", b =>
                {
                    b.HasOne("BloodBankManagementSystem.Models.DonorRecord", "Donor")
                        .WithMany()
                        .HasForeignKey("DonorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Donor");
                });

            modelBuilder.Entity("BloodBankManagementSystem.Models.BloodRequest", b =>
                {
                    b.HasOne("BloodBankManagementSystem.Models.BloodInventory", "BloodInventory")
                        .WithMany()
                        .HasForeignKey("InventoryId");

                    b.HasOne("BloodBankManagementSystem.Models.PatientRecord", "PatientRecord")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BloodInventory");

                    b.Navigation("PatientRecord");
                });

            modelBuilder.Entity("BloodBankManagementSystem.Models.Consent", b =>
                {
                    b.HasOne("BloodBankManagementSystem.Models.DonorRecord", "Donor")
                        .WithOne("Consent")
                        .HasForeignKey("BloodBankManagementSystem.Models.Consent", "DonorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Donor");
                });

            modelBuilder.Entity("BloodBankManagementSystem.Models.DonorRecord", b =>
                {
                    b.HasOne("BloodBankManagementSystem.Models.DoctorInformation", "DoctorInformation")
                        .WithMany()
                        .HasForeignKey("DoctorId");

                    b.HasOne("BloodBankManagementSystem.Models.PatientRecord", "PatientRecord")
                        .WithMany()
                        .HasForeignKey("PatientId");

                    b.Navigation("DoctorInformation");

                    b.Navigation("PatientRecord");
                });

            modelBuilder.Entity("BloodBankManagementSystem.Models.PatientRecord", b =>
                {
                    b.HasOne("BloodBankManagementSystem.Models.Billing", "Billing")
                        .WithMany()
                        .HasForeignKey("BillId");

                    b.HasOne("BloodBankManagementSystem.Models.HospitalInformation", "HospitalInformation")
                        .WithMany()
                        .HasForeignKey("HospitalId");

                    b.Navigation("Billing");

                    b.Navigation("HospitalInformation");
                });

            modelBuilder.Entity("BloodBankManagementSystem.Models.DonorRecord", b =>
                {
                    b.Navigation("Consent");
                });
#pragma warning restore 612, 618
        }
    }
}
